root | DEBUG | 2020-11-22 17:21:41,471 | Number of entries 29
root | DEBUG | 2020-11-22 17:22:03,961 | Number of entries 29
root | DEBUG | 2020-11-22 17:22:29,548 | Number of entries 29
root | DEBUG | 2020-11-22 17:26:16,529 | Number of entries 29
root | DEBUG | 2020-11-22 17:28:01,382 | Number of entries 28
root | DEBUG | 2020-11-22 17:28:24,673 | Number of entries 28
root | DEBUG | 2020-11-22 17:28:27,310 | Number of entries 28
root | DEBUG | 2020-11-22 17:29:26,133 | Number of entries 28
root | DEBUG | 2020-11-22 17:37:09,724 | Number of entries 28
root | DEBUG | 2020-11-22 17:37:15,290 | Number of entries 28
root | DEBUG | 2020-11-22 17:39:34,918 | Number of entries 28
root | DEBUG | 2020-11-22 17:49:21,937 | Number of entries 28
root | DEBUG | 2020-11-22 17:59:56,567 | Number of entries 28
root | ERROR | 2020-11-22 17:59:56,614 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:00:56,366 | Number of entries 28
root | ERROR | 2020-11-22 18:00:56,369 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:01:17,176 | Number of entries 28
root | ERROR | 2020-11-22 18:01:17,178 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:06:35,993 | Number of entries 28
root | ERROR | 2020-11-22 18:06:35,997 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:06:35,999 | Number of entries 57
root | DEBUG | 2020-11-22 18:10:12,629 | Number of entries 28
root | ERROR | 2020-11-22 18:10:12,631 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:10:12,635 | Number of entries 57
root | DEBUG | 2020-11-22 18:14:20,640 | Number of entries 28
root | ERROR | 2020-11-22 18:14:20,643 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:14:20,647 | Number of entries 57
root | DEBUG | 2020-11-22 18:16:12,293 | Number of entries 28
root | ERROR | 2020-11-22 18:16:12,296 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:16:12,300 | Number of entries 57
root | DEBUG | 2020-11-22 18:18:21,299 | Number of entries 28
root | ERROR | 2020-11-22 18:18:21,301 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 33, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:18:21,305 | Number of entries 57
root | DEBUG | 2020-11-22 18:19:13,558 | Number of entries 28
root | ERROR | 2020-11-22 18:19:13,562 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 33, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 18:19:13,564 |  Exception occurred due to wrong file extension
NoneType: None
root | DEBUG | 2020-11-22 18:20:09,403 | Number of entries 28
root | ERROR | 2020-11-22 18:20:09,405 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 18:20:09,408 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-22 18:21:07,806 | Number of entries 28
root | ERROR | 2020-11-22 18:21:07,808 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 18:21:07,811 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-22 19:04:02,860 | Number of entries 28
root | ERROR | 2020-11-22 19:04:02,896 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:04:02,899 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-22 19:11:34,595 | Number of entries 28
root | ERROR | 2020-11-22 19:11:34,598 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:11:34,602 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 19:11:34,605 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | DEBUG | 2020-11-22 19:19:54,469 | Number of entries 28
root | ERROR | 2020-11-22 19:19:54,505 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:19:54,519 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 19:19:54,522 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 19:19:54,525 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 19:33:01,614 | Number of records: 29
root | ERROR | 2020-11-22 19:33:01,695 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 40, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:33:01,701 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 19:33:01,706 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 40, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 19:33:01,710 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 40, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 19:34:04,455 | Number of records: 28
root | ERROR | 2020-11-22 19:34:04,458 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:34:04,461 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 19:34:04,463 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 19:34:04,465 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 19:39:54,577 | Number of records: 28
root | ERROR | 2020-11-22 19:39:54,579 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:39:54,582 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 19:39:54,584 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 19:39:54,585 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 19:39:54,619 | Number of records: 36
root | DEBUG | 2020-11-22 19:40:07,260 | Number of records: 28
root | ERROR | 2020-11-22 19:40:07,263 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:40:07,265 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 19:40:07,267 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 19:40:07,269 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 19:40:07,271 | Number of records: 36
root | DEBUG | 2020-11-22 19:42:46,872 | Number of records: 28
root | ERROR | 2020-11-22 19:42:46,875 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:42:46,879 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 19:42:46,882 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 19:42:46,885 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 19:42:46,889 | Number of records: 36
root | DEBUG | 2020-11-22 20:42:12,099 | Number of records: 28
root | ERROR | 2020-11-22 20:42:12,146 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 20:42:12,151 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 20:42:12,154 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 20:42:12,156 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 20:42:12,160 | Number of records: 36
root | DEBUG | 2020-11-22 20:45:07,550 | Number of records: 28
root | ERROR | 2020-11-22 20:45:07,554 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 20:45:07,558 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 20:45:07,561 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 20:45:07,565 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 20:45:07,569 | Number of records: 36
root | ERROR | 2020-11-22 20:45:07,572 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/StateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | DEBUG | 2020-11-22 20:53:19,719 | Number of records: 28
root | ERROR | 2020-11-22 20:53:19,722 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 20:53:19,725 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 20:53:19,728 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 20:53:19,730 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 20:53:19,733 | Number of records: 36
root | ERROR | 2020-11-22 20:53:19,735 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/StateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-22 20:53:19,737 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 07:53:12,987 | Number of records: 28
root | ERROR | 2020-11-23 07:53:13,023 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-23 07:53:13,041 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-23 07:53:13,044 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-23 07:53:13,047 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-23 07:53:13,051 | Number of records: 36
root | ERROR | 2020-11-23 07:53:13,054 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/StateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-23 07:53:13,057 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 12:15:02,248 | Number of records: 28
root | ERROR | 2020-11-23 12:15:02,284 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-23 12:15:02,289 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-23 12:15:02,293 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-23 12:15:02,297 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-23 12:15:02,302 | Number of records: 36
root | ERROR | 2020-11-23 12:15:02,318 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/StateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-23 12:15:02,321 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 13:47:04,581 | Number of records: 28
root | ERROR | 2020-11-23 13:47:04,628 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-23 13:47:04,634 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-23 13:47:04,639 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-23 13:47:04,642 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-23 13:47:04,647 | Number of records: 36
root | ERROR | 2020-11-23 13:47:04,673 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/StateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-23 13:47:04,677 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 13:47:23,094 | Number of records: 28
root | ERROR | 2020-11-23 13:47:23,098 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-23 13:47:23,102 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-23 13:47:23,107 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-23 13:47:23,111 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-23 13:47:23,115 | Number of records: 36
root | ERROR | 2020-11-23 13:47:23,119 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/StateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-23 13:47:23,122 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 19:23:11,761 | Number of records: 28
root | ERROR | 2020-11-23 19:23:11,797 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-23 19:23:11,801 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-23 19:23:11,806 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-23 19:23:11,810 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-23 19:23:11,814 | Number of records: 36
root | ERROR | 2020-11-23 19:23:11,842 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/StateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-23 19:23:11,845 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 19:52:17,662 | Number of records: 28
root | ERROR | 2020-11-23 19:52:17,691 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_CensusAnalyzer/IndiaStateCensusData.csv'
root | ERROR | 2020-11-23 19:52:17,697 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 19:52:17,714 | Number of records: 28
root | ERROR | 2020-11-23 19:52:17,731 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-23 19:52:17,734 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-23 19:52:17,750 | Number of records: 36
root | ERROR | 2020-11-23 19:52:17,776 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/StateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-23 19:52:17,779 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 19:54:37,468 | Number of records: 28
root | ERROR | 2020-11-23 19:54:37,471 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_CensusAnalyzer/IndiaStateCensusData.csv'
root | ERROR | 2020-11-23 19:54:37,474 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 19:54:37,476 | Number of records: 28
root | ERROR | 2020-11-23 19:54:37,479 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-23 19:54:37,515 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-23 19:54:37,517 | Number of records: 36
root | ERROR | 2020-11-23 19:54:37,519 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/StateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-23 19:54:37,521 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 19:56:37,669 | Number of records: 28
root | ERROR | 2020-11-23 19:56:37,672 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_CensusAnalyzer/IndiaStateCensusData.csv'
root | ERROR | 2020-11-23 19:56:37,675 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 19:56:37,678 | Number of records: 28
root | ERROR | 2020-11-23 19:56:37,680 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-23 19:56:37,714 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-23 19:56:37,718 | Number of records: 36
root | ERROR | 2020-11-23 19:56:37,720 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/StateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-23 19:56:37,723 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 19:58:07,313 | Number of records: 28
root | ERROR | 2020-11-23 19:58:07,317 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_CensusAnalyzer/IndiaStateCensusData.csv'
root | ERROR | 2020-11-23 19:58:07,319 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 19:58:07,322 | Number of records: 28
root | ERROR | 2020-11-23 19:58:07,324 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-23 19:58:07,358 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-23 19:58:07,360 | Number of records: 36
root | ERROR | 2020-11-23 19:58:07,363 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/StateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-23 19:58:07,365 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 19:59:41,116 | Number of records: 28
root | ERROR | 2020-11-23 19:59:41,118 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_CensusAnalyzer/IndiaStateCensusData.csv'
root | ERROR | 2020-11-23 19:59:41,121 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 19:59:41,124 | Number of records: 28
root | ERROR | 2020-11-23 19:59:41,127 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-23 19:59:41,163 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-23 19:59:41,165 | Number of records: 36
root | ERROR | 2020-11-23 19:59:41,167 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/StateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-23 19:59:41,170 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 20:00:16,832 | Number of records: 28
root | ERROR | 2020-11-23 20:00:16,836 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_CensusAnalyzer/IndiaStateCensusData.csv'
root | ERROR | 2020-11-23 20:00:16,840 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 20:00:16,842 | Number of records: 28
root | ERROR | 2020-11-23 20:00:16,844 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-23 20:00:16,846 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-23 20:00:16,850 | Number of records: 36
root | ERROR | 2020-11-23 20:00:16,854 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/StateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-23 20:00:16,857 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 20:01:55,210 | Number of records: 28
root | ERROR | 2020-11-23 20:01:55,214 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_CensusAnalyzer/IndiaStateCensusData.csv'
root | ERROR | 2020-11-23 20:01:55,218 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 20:01:55,222 | Number of records: 28
root | ERROR | 2020-11-23 20:01:55,225 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects//IndianStateCensusAnalyzer/test_CensusAnalyzer/delimeter_census_data.csv'
root | ERROR | 2020-11-23 20:01:55,229 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_CensusAnalyzer/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-23 20:01:55,233 | Number of records: 36
root | ERROR | 2020-11-23 20:01:55,236 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-23 20:01:55,239 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 20:02:01,534 | Number of records: 28
root | ERROR | 2020-11-23 20:02:01,537 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_CensusAnalyzer/IndiaStateCensusData.csv'
root | ERROR | 2020-11-23 20:02:01,540 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 20:02:01,543 | Number of records: 28
root | ERROR | 2020-11-23 20:02:01,546 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects//IndianStateCensusAnalyzer/test_CensusAnalyzer/delimeter_census_data.csv'
root | ERROR | 2020-11-23 20:02:01,549 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_CensusAnalyzer/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-23 20:02:01,552 | Number of records: 36
root | ERROR | 2020-11-23 20:02:01,556 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-23 20:02:01,560 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 20:03:03,932 | Number of records: 28
root | ERROR | 2020-11-23 20:03:03,934 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_CensusAnalyzer/IndiaStateCensusData.csv'
root | ERROR | 2020-11-23 20:03:03,937 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-23 20:03:03,939 | Number of records: 28
root | ERROR | 2020-11-23 20:03:03,942 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_CensusAnalyzer/delimeter_census_data.csv'
root | ERROR | 2020-11-23 20:03:03,945 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_CensusAnalyzer/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-23 20:03:03,949 | Number of records: 36
root | ERROR | 2020-11-23 20:03:03,952 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/test_StateCensusAnalyzer/IndiaStateCode.csv'
root | ERROR | 2020-11-23 20:03:03,955 |  Exception occurred due to wrong file extension
