root | DEBUG | 2020-11-22 17:21:41,471 | Number of entries 29
root | DEBUG | 2020-11-22 17:22:03,961 | Number of entries 29
root | DEBUG | 2020-11-22 17:22:29,548 | Number of entries 29
root | DEBUG | 2020-11-22 17:26:16,529 | Number of entries 29
root | DEBUG | 2020-11-22 17:28:01,382 | Number of entries 28
root | DEBUG | 2020-11-22 17:28:24,673 | Number of entries 28
root | DEBUG | 2020-11-22 17:28:27,310 | Number of entries 28
root | DEBUG | 2020-11-22 17:29:26,133 | Number of entries 28
root | DEBUG | 2020-11-22 17:37:09,724 | Number of entries 28
root | DEBUG | 2020-11-22 17:37:15,290 | Number of entries 28
root | DEBUG | 2020-11-22 17:39:34,918 | Number of entries 28
root | DEBUG | 2020-11-22 17:49:21,937 | Number of entries 28
root | DEBUG | 2020-11-22 17:59:56,567 | Number of entries 28
root | ERROR | 2020-11-22 17:59:56,614 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:00:56,366 | Number of entries 28
root | ERROR | 2020-11-22 18:00:56,369 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:01:17,176 | Number of entries 28
root | ERROR | 2020-11-22 18:01:17,178 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:06:35,993 | Number of entries 28
root | ERROR | 2020-11-22 18:06:35,997 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:06:35,999 | Number of entries 57
root | DEBUG | 2020-11-22 18:10:12,629 | Number of entries 28
root | ERROR | 2020-11-22 18:10:12,631 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:10:12,635 | Number of entries 57
root | DEBUG | 2020-11-22 18:14:20,640 | Number of entries 28
root | ERROR | 2020-11-22 18:14:20,643 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:14:20,647 | Number of entries 57
root | DEBUG | 2020-11-22 18:16:12,293 | Number of entries 28
root | ERROR | 2020-11-22 18:16:12,296 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:16:12,300 | Number of entries 57
root | DEBUG | 2020-11-22 18:18:21,299 | Number of entries 28
root | ERROR | 2020-11-22 18:18:21,301 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 33, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | DEBUG | 2020-11-22 18:18:21,305 | Number of entries 57
root | DEBUG | 2020-11-22 18:19:13,558 | Number of entries 28
root | ERROR | 2020-11-22 18:19:13,562 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 33, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 18:19:13,564 |  Exception occurred due to wrong file extension
NoneType: None
root | DEBUG | 2020-11-22 18:20:09,403 | Number of entries 28
root | ERROR | 2020-11-22 18:20:09,405 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 18:20:09,408 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-22 18:21:07,806 | Number of entries 28
root | ERROR | 2020-11-22 18:21:07,808 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 18:21:07,811 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-22 19:04:02,860 | Number of entries 28
root | ERROR | 2020-11-22 19:04:02,896 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:04:02,899 |  Exception occurred due to wrong file extension
root | DEBUG | 2020-11-22 19:11:34,595 | Number of entries 28
root | ERROR | 2020-11-22 19:11:34,598 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:11:34,602 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 19:11:34,605 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | DEBUG | 2020-11-22 19:19:54,469 | Number of entries 28
root | ERROR | 2020-11-22 19:19:54,505 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:19:54,519 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 19:19:54,522 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 19:19:54,525 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 26, in load_census_data
    with open(csv_file_path, 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 19:33:01,614 | Number of records: 29
root | ERROR | 2020-11-22 19:33:01,695 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 40, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:33:01,701 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 19:33:01,706 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 40, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 19:33:01,710 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 40, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 19:34:04,455 | Number of records: 28
root | ERROR | 2020-11-22 19:34:04,458 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:34:04,461 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 19:34:04,463 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 19:34:04,465 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 19:39:54,577 | Number of records: 28
root | ERROR | 2020-11-22 19:39:54,579 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:39:54,582 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 19:39:54,584 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 19:39:54,585 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 19:39:54,619 | Number of records: 36
root | DEBUG | 2020-11-22 19:40:07,260 | Number of records: 28
root | ERROR | 2020-11-22 19:40:07,263 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:40:07,265 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 19:40:07,267 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 19:40:07,269 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 19:40:07,271 | Number of records: 36
root | DEBUG | 2020-11-22 19:42:46,872 | Number of records: 28
root | ERROR | 2020-11-22 19:42:46,875 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/IndiaStateCensusData.csv'
root | ERROR | 2020-11-22 19:42:46,879 |  Exception occurred due to wrong file extension
root | ERROR | 2020-11-22 19:42:46,882 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/delimeter_census_data.csv'
root | ERROR | 2020-11-22 19:42:46,885 | File Path Error Exception,Incorrect File Path Input 
Traceback (most recent call last):
  File "/home/shubh/PycharmProjects/IndianStateCensusAnalyzer/Main_CensusAnalyzer/Census_Analyzer.py", line 24, in load_census_data
    with open(csv_file_path, 'r') as census_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubh/PycharmProjects/test_UserRegistration/MissingHeader_StateCensusData.csv'
root | DEBUG | 2020-11-22 19:42:46,889 | Number of records: 36
